language: node_js
node_js:
  - node
  - 8
script:
  - npm run build
  - npm run test
  - npm run lint
  - nyc --silent npm run test
  - nyc report --reporter=text-lcov | coveralls
  - nyc check-coverage --lines 60
after_success:
  - npm run build
  - semantic-release
notifications:
  email: false
sudo: false
